/* tslint:disable */
/* eslint-disable */
/**
 * FamilyPoints - OpenAPI 3.0
 * Documentacion de la aplicaion FamilyPoints. Una aplicación para gestionar el intercambio de favores entre miembros de la misma familia (quedarse una noche con los niños, cocinar para toda la semana, etc.), qué se acumularán como puntos canjeables por actividades lúdicas (noche libre con amigos, spa, tarde de videojuegos, etc.).    `Trabajo Final de Grado, Universidad de Alicante 2023-24.`   `Autor: Robert Kazaryan.`
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./base";
export * from "./configuration";

